run:
  timeout: 5m
  issues:
    exclude-dirs:
      - test

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - goconst
    - gocyclo
    - dupl
    - misspell
    - revive

linters-settings:
  gocyclo:
    min-complexity: 25
  goconst:
    min-len: 3
    min-occurrences: 4
  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst
        - gocyclo
    - path: test/
      linters:
        - dupl
        - goconst
    - path: internal/api/handlers.go
      linters:
        - dupl
